// All the predefined lists can be found here and all the variables associated to the lists length are at the bottom

// Street names
const street_names = [
    "Broadway",
    "Fifth Avenue",
    "Park Avenue",
    "Madison Avenue",
    "Lexington Avenue",
    "Wall Street",
    "Canal Street",
    "Bowery",
    "Houston Street",
    "Bleecker Street",
    "Mulberry Street",
    "Delancey Street",
    "Orchard Street",
    "Allen Street",
    "Eldridge Street",
    "Ludlow Street",
    "Rivington Street",
    "St. Marks Place",
    "Avenue A",
    "Avenue B",
    "Avenue C",
    "Avenue D",
    "1st Avenue",
    "2nd Avenue",
    "3rd Avenue",
    "4th Avenue",
    "5th Avenue",
    "6th Avenue",
    "7th Avenue",
    "8th Avenue",
    "9th Avenue",
    "10th Avenue",
    "11th Avenue",
    "12th Avenue",
    "Central Park West",
    "Columbus Circle",
    "West End Avenue",
    "Riverside Drive",
    "Amsterdam Avenue",
    "Broadway",
    "Ninth Avenue",
    "Tenth Avenue",
    "Eleventh Avenue",
    "Twelfth Avenue",
    "Lenox Avenue",
    "Frederick Douglass Boulevard",
    "Morningside Drive",
    "St. Nicholas Avenue",
    "Edgecombe Avenue",
    "Adam Clayton Powell Jr. Boulevard",
];

// Island locations
const island_locations = [
    "Greece",
    "North Sea",
    "Ireland",
    "United Kingdom",
    "France",
    "Belgium",
    "Netherlands",
    "Denmark",
    "Norway",
    "Sweden",
    "Caribbean",
    "Bahamas",
    "Cuba",
    "Haiti",
    "Dominican Republic",
    "Jamaica",
    "Maldives",
    "Fiji",
    "Hawaii",
    "Seychelles",
    "New Zealand",
    "Iceland",
    "Japan",
    "Philippines",
    "Indonesia",
    "Madagascar",
    "Sri Lanka",
    "Mauritius",
    "Bora Bora",
    "Tahiti",
    "Galápagos Islands",
    "Bali",
    "Sicily",
    "Crete",
    "Cyprus"
];

// Planet names
const planet_locations = [
    "Tatooine",
    "Mars",
    "Pandora",
    "Vulcan",
    "Naboo",
    "Krypton",
    "Gallifrey",
    "Dune",
    "Hoth",
    "Endor",
    "Arrakis",
    "Coruscant",
    "Dagobah",
    "Mustafar",
    "Alderaan",
    "Bespin",
    "Yavin IV",
    "Kashyyyk",
    "Kamino",
    "Geonosis",
    "Lothal",
    "Jedha",
    "Scarif",
    "Crait",
    "Batuu",
    "Exegol",
    "Hoth",
    "Jakku",
    "Malachor",
    "Mortis",
    "Myrkr",
    "Ossus",
    "Ryloth",
    "Sullust",
    "Tython",
    "Umbara",
    "Yavin IV",
    "Zonama Sekot",
    "Titan",
    "Triton",
    "Europa",
    "Ganymede",
    "Io",
    "Callisto",
    "Enceladus",
    "Rhea",
    "Mimas",
    "Tethys",
    "Iapetus",
    "Dione",
    "Eris",
    "Haumea",
    "Makemake",
    "Ceres",
    "Vesta",
    "Charon",
    "Pluto",
    "Titania",
    "Oberon",
    "Ariel",
    "Umbriel",
    "Miranda",
    "Hyperion",
    "Proteus",
    "Nereid",
    "Phobos",
    "Deimos",
    "Styx",
    "Hydra",
    "Nix",
    "Kerberos",
    "Sedna",
    "Quaoar",
    "Orcus",
    "Ixion",
    "Varuna",
    "Salacia",
    "Gonggong",
    "V774104",
    "2002 MS4"
];

const education = {
    "High School": [
        { name: "General Education", length: 5, salary: 35000 }
    ],
    "Community College": [
        { name: "General Education", length: 2, salary: 40000 },
        { name: "Technical Studies", length: 2, salary: 45000 },
        { name: "Business", length: 2, salary: 50000 },
        { name: "Health Sciences", length: 2, salary: 55000 },
        { name: "Computer Science", length: 2, salary: 60000 },
        { name: "Engineering", length: 2, salary: 60000 },
        { name: "Dental Hygiene", length: 2, salary: 60000 },
        { name: "Nursing", length: 2, salary: 60000 },
        { name: "Criminal Justice", length: 2, salary: 60000 }
    ],
    "University": [
        { name: "Arts", length: 4, salary: 45000 },
        { name: "Sciences", length: 4, salary: 60000 },
        { name: "Business", length: 4, salary: 70000 },
        { name: "Engineering", length: 4, salary: 80000 },
        { name: "Health Sciences", length: 4, salary: 75000 },
        { name: "Computer Science", length: 4, salary: 80000 },
        { name: "Education", length: 4, salary: 70000 },
        { name: "Law", length: 4, salary: 90000 },
        { name: "Medicine", length: 4, salary: 100000 },
        { name: "Dentistry", length: 4, salary: 100000 },
        { name: "Pharmacy", length: 4, salary: 90000 },
        { name: "Nursing", length: 4, salary: 80000 },
        { name: "Criminal Justice", length: 4, salary: 80000 },
        { name: "Social Work", length: 4, salary: 70000 },
        { name: "Public Health", length: 4, salary: 70000 },
        { name: "Psychology", length: 4, salary: 60000 },
        { name: "Sociology", length: 4, salary: 60000 },
        { name: "Public Administration", length: 4, salary: 70000 },
        { name: "Environmental Science", length: 4, salary: 65000 },
        { name: "Political Science", length: 4, salary: 70000 },
        { name: "History", length: 4, salary: 55000 },
        { name: "Philosophy", length: 4, salary: 50000 },
        { name: "Religion", length: 4, salary: 45000 },
        { name: "Theology", length: 4, salary: 45000 },
        { name: "Music", length: 4, salary: 45000 },
        { name: "Art", length: 4, salary: 45000 },
        { name: "Dance", length: 4, salary: 45000 },
        { name: "Theatre", length: 4, salary: 45000 },
        { name: "Film", length: 4, salary: 45000 },
        { name: "Journalism", length: 4, salary: 45000 },
        { name: "Communication", length: 4, salary: 45000 },
        { name: "Marketing", length: 4, salary: 50000 },
        { name: "Finance", length: 4, salary: 60000 },
        { name: "Accounting", length: 4, salary: 60000 },
        { name: "Economics", length: 4, salary: 60000 },
        { name: "Mathematics", length: 4, salary: 60000 },
        { name: "Physics", length: 4, salary: 60000 },
        { name: "Chemistry", length: 4, salary: 60000 },
        { name: "Biology", length: 4, salary: 60000 },
        { name: "Geology", length: 4, salary: 60000 },
        { name: "Astronomy", length: 4, salary: 60000 },
        { name: "Software Engineering", length: 4, salary: 65000 },
        { name: "Electrical Engineering", length: 4, salary: 70000 },
        { name: "Mechanical Engineering", length: 4, salary: 70000 },
        { name: "Civil Engineering", length: 4, salary: 70000 },
        { name: "Chemical Engineering", length: 4, salary: 70000 },
        { name: "Biomedical Engineering", length: 4, salary: 75000 },
        { name: "Aerospace Engineering", length: 4, salary: 75000 },
        { name: "Industrial Engineering", length: 4, salary: 75000 },
        { name: "Materials Engineering", length: 4, salary: 75000 },
        { name: "Nuclear Engineering", length: 4, salary: 75000 },
        { name: "Physical Therapy", length: 4, salary: 75000 },
        { name: "Occupational Therapy", length: 4, salary: 75000 },
        { name: "Speech Therapy", length: 4, salary: 75000 },
        { name: "Physician Assistant", length: 4, salary: 75000 },
        { name: "Veterinary Medicine", length: 4, salary: 75000 },
        { name: "Optometry", length: 4, salary: 75000 },
        { name: "Physical Education", length: 4, salary: 45000 }
    ]
};

// Months and days
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

